import type { Plugin } from "vite";

const PUBLIC_ASSETS = [
  "/",
  "/index.html",
  "/manifest.json",
  "/epub-frame-bridge.js",
  "/icon-192.png",
  "/icon-512.png",
  "/ragdoll-32.png",
];

function cacheKey(paths: string[]): string {
  let hash = 2166136261;
  for (const char of paths.join("\n")) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

/**
 * PDF 阅读器是按需入口，其渲染器和 Worker 体积较大。它们仍会在首次打开时
 * 被下方的 cache-first 策略缓存，但不应拖慢普通笔记用户安装或更新 PWA。
 */
export function shouldPrecache(path: string): boolean {
  if (path.endsWith(".map")) return false;
  return !/^\/assets\/(?:pdfjs-|PdfReader-|pdf\.worker)/.test(path);
}

export function createServiceWorkerSource(generatedFiles: string[], buildId: string): string {
  const generatedAssets = generatedFiles
    .map((fileName) => `/${fileName}`)
    .filter(shouldPrecache);
  const precache = [...new Set([...PUBLIC_ASSETS, ...generatedAssets])].sort();
  const cacheName = `nine-rings-${cacheKey([...precache, buildId])}`;

  return `/* Generated by plugins/vite-pwa-plugin.ts. Do not edit. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(installVersion());
});

async function installVersion() {
  let failure;
  try {
    const cache = await caches.open(CACHE_NAME);
    let next = 0;
    // Bound network and CacheStorage pressure on mobile. Activation still waits
    // for the entire version; partially downloaded versions are never served.
    await Promise.all(Array.from({ length: 4 }, async () => {
      while (!failure && next < PRECACHE.length) {
        const url = PRECACHE[next++];
        try {
          await cacheResource(cache, url);
        } catch (error) {
          failure ||= error;
        }
      }
    }));
    if (failure) throw failure;
  } catch (error) {
    // All writers have settled before removing this failed version's cache.
    // Never touch IndexedDB or the active version's offline cache.
    await caches.delete(CACHE_NAME).catch(() => {});
    const details = "build=" + ${JSON.stringify(buildId)} + " cache=" + CACHE_NAME + "\\n" + String(error);
    try {
      const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of clients) client.postMessage({ type: "PWA_INSTALL_FAILED", details });
    } catch { /* Reporting must not mask the installation error. */ }
    throw error;
  }
}

async function cacheResource(cache, url) {
  for (let attempt = 1; attempt <= 3; attempt++) {
    const controller = new AbortController();
    let timedOut = false;
    const timer = setTimeout(() => { timedOut = true; controller.abort(); }, 15000);
    let stage = "download";
    let status = "unavailable";
    try {
      const request = new Request(url, { cache: "reload" });
      const response = await fetch(request, { signal: controller.signal });
      status = response.status;
      if (!response.ok) throw new Error("HTTP " + status);
      // A deployment fallback must not silently cache HTML as a script/style.
      const type = response.headers.get("content-type") || "";
      if (/\\.(?:m?js|css)$/.test(url) && type.includes("text/html")) {
        throw new Error("Unexpected HTML response");
      }
      // HTTP headers (including 200) can arrive before the response body.
      // Finish the abortable download before handing bytes to CacheStorage.
      stage = "body-read";
      const body = await response.arrayBuffer();
      clearTimeout(timer);
      const headers = new Headers(response.headers);
      // fetch has already decoded content encodings; these bytes are complete.
      headers.delete("content-encoding");
      headers.delete("content-length");
      stage = "cache-write";
      await cache.put(request, new Response(body, { status: response.status, statusText: response.statusText, headers }));
      return;
    } catch (error) {
      const transientWrite = error?.name === "AbortError" || error?.name === "NetworkError";
      if (attempt === 3 || (stage === "cache-write" && !transientWrite)) {
        throw new Error("resource=" + url + " stage=" + stage + " status=" + status + " attempt=" + attempt + " timeout=" + timedOut + " " + String(error));
      }
    } finally {
      clearTimeout(timer);
    }
    await new Promise((resolve) => setTimeout(resolve, attempt * 500));
  }
}

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("nine-rings-") && key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname === "/__import") return;

  if (request.mode === "navigate" || request.destination === "document") {
    // HTML 与当前版本预缓存的哈希资源必须保持原子性。不能用后台
    // 网络请求改写旧版缓存中的 HTML，否则新入口会引用旧缓存不存在的模块。
    // 新版本只由新 Service Worker 的 install/activate 整体替换。
    event.respondWith(
      caches.open(CACHE_NAME)
        .then((cache) => cache.match(request).then((cached) => cached || cache.match("/index.html")))
        .then((cached) => cached || fetch(request))
        .catch(() => Response.error())
    );
    return;
  }

  if (["script", "style", "font", "image", "worker"].includes(request.destination)) {
    event.respondWith(cacheFirst(request));
  }
});

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    await cache.put(request, response.clone());
  }
  return response;
}

`;
}

/** Generate a versioned service worker from the actual hashed Vite output. */
export default function pwaPlugin(buildId: string): Plugin {
  return {
    name: "nine-rings-pwa",
    apply: "build",
    generateBundle: {
      // Vite removes pure-CSS JS chunks in its own generateBundle hook.
      // Snapshot only after those hooks, otherwise every install hits a 404.
      order: "post",
      handler(_options, bundle) {
        const source = createServiceWorkerSource(Object.values(bundle).map((entry) => entry.fileName), buildId);
        this.emitFile({ type: "asset", fileName: "sw.js", source });
      },
    },
  };
}
