import type { Plugin } from "vite";

const PUBLIC_ASSETS = [
  "/",
  "/index.html",
  "/manifest.json",
  "/icon-192.png",
  "/icon-512.png",
  "/ragdoll-32.png",
];

function cacheKey(paths: string[]): string {
  let hash = 2166136261;
  for (const char of paths.join("\n")) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

export function createServiceWorkerSource(generatedFiles: string[], buildId: string): string {
  const generatedAssets = generatedFiles
    .map((fileName) => `/${fileName}`)
    .filter((path) => !path.endsWith(".map"));
  const precache = [...new Set([...PUBLIC_ASSETS, ...generatedAssets])].sort();
  const cacheName = `nine-rings-${cacheKey([...precache, buildId])}`;

  return `/* Generated by plugins/vite-pwa-plugin.ts. Do not edit. */
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("nine-rings-") && key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || url.pathname === "/__import") return;

  if (request.mode === "navigate" || request.destination === "document") {
    // 已安装的 PWA 优先显示本地应用外壳，同时在后台更新 HTML。旧实现会在
    // 每次冷启动时无限等待网络，即使全部资源已缓存，也会先出现白屏。
    const refresh = refreshNavigation(request);
    event.respondWith(
      caches.match(request)
        .then((cached) => cached || caches.match("/index.html"))
        .then((cached) => cached || refresh)
        .catch(() => Response.error())
    );
    event.waitUntil(refresh.then(() => undefined).catch(() => undefined));
    return;
  }

  if (["script", "style", "font", "image", "worker"].includes(request.destination)) {
    event.respondWith(cacheFirst(request));
  }
});

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(request, response.clone());
  }
  return response;
}

async function refreshNavigation(request) {
  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(request, response.clone());
  }
  return response;
}
`;
}

/** Generate a versioned service worker from the actual hashed Vite output. */
export default function pwaPlugin(buildId: string): Plugin {
  return {
    name: "nine-rings-pwa",
    apply: "build",
    generateBundle(_options, bundle) {
      const source = createServiceWorkerSource(Object.values(bundle).map((entry) => entry.fileName), buildId);
      this.emitFile({ type: "asset", fileName: "sw.js", source });
    },
  };
}
