import { expect, test } from "@playwright/test";
import { waitForSavedText } from "./helpers/document";
import { openDocumentSidebar, openMobileDocumentPopup } from "./helpers/workspace";
import { pressLineBoundary } from "./helpers/keyboard";

test("随记位于文档列表之后，普通文档支持待办、多选分组、改名及刷新恢复", async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem("nr:sidebarOrder", "tree,list,reader");
    localStorage.setItem("nr:sidebarHidden", "false");
  });
  await page.goto("/");
  const rail = page.getByRole("navigation", { name: "工作区面板" });
  await expect.poll(() => rail.locator("[data-sidebar-panel]").evaluateAll(items => items.map(item => item.getAttribute("aria-label"))))
    .toEqual(["文档树", "文档列表", "随记", "PDF / EPUB 阅读"]);
  await rail.getByRole("button", { name: "随记", exact: true }).click();
  const panel = page.getByRole("region", { name: "随记列表", exact: true });
  await expect(panel).toBeVisible();
  await panel.getByRole("button", { name: "新建随记", exact: true }).click();
  await expect(page.locator(".note-title")).toHaveValue(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
  await page.locator(".note-title").fill("临时想法");
  await page.locator(".ProseMirror").fill("先记录再整理。");
  await waitForSavedText(page, "先记录再整理。");
  await expect(panel.getByRole("button", { name: "重命名随记 临时想法", exact: true })).toBeVisible();
  const firstId = await page.evaluate(() => localStorage.getItem("nr:lastNote"));
  await panel.getByRole("button", { name: "新建随记", exact: true }).click();
  await expect.poll(() => page.evaluate(() => localStorage.getItem("nr:lastNote"))).not.toBe(firstId);
  await expect(page.locator(".note-title")).toHaveValue(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
  await expect(page.locator(".ProseMirror")).toHaveText("");
  await page.locator(".note-title").fill("待办随记");
  const editor = page.locator(".ProseMirror");
  await editor.pressSequentially("/todo ");
  const task = editor.getByRole("checkbox", { name: "任务完成状态" });
  await expect(task).toHaveAttribute("aria-checked", "false");
  await editor.pressSequentially("完成回归");
  await task.click();
  await expect(task).toHaveAttribute("aria-checked", "true");
  await editor.press("ControlOrMeta+z");
  await expect(task).toHaveAttribute("aria-checked", "false");
  await waitForSavedText(page, "完成回归");
  await task.click();
  await editor.locator("li p").click();
  await pressLineBoundary(editor, "end");
  await editor.press("Enter");
  const tasks = editor.getByRole("checkbox", { name: "任务完成状态" });
  await expect(tasks).toHaveCount(2);
  await expect(tasks.nth(0)).toHaveAttribute("aria-checked", "true");
  await expect(tasks.nth(1)).toHaveAttribute("aria-checked", "false");
  await editor.pressSequentially("后续待办");
  await editor.press("Enter");
  await editor.press("Enter");
  await expect(tasks).toHaveCount(2);
  await expect(editor.locator(":scope > p")).toHaveCount(1);
  await waitForSavedText(page, "后续待办");
  await panel.getByRole("button", { name: "多选随记", exact: true }).click();
  await panel.getByRole("checkbox", { name: "选择随记 临时想法", exact: true }).check();
  await panel.getByRole("checkbox", { name: "选择随记 待办随记", exact: true }).check();
  await panel.getByRole("button", { name: "分组", exact: true }).click();
  await expect(panel.getByLabel("分组名称", { exact: true })).toHaveValue(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
  await panel.getByLabel("分组名称", { exact: true }).fill("本周");
  await panel.getByRole("button", { name: "确定", exact: true }).click();
  await expect(panel.getByRole("region", { name: "本周", exact: true }).locator(".notes-panel-row")).toHaveCount(2);
  await panel.getByRole("button", { name: "重命名分组 本周", exact: true }).click();
  await panel.getByLabel("分组名称", { exact: true }).fill("近期");
  await panel.getByRole("button", { name: "确定", exact: true }).click();
  await expect(panel.getByRole("region", { name: "近期", exact: true }).locator(".notes-panel-row")).toHaveCount(2);
  await panel.getByRole("button", { name: "重命名随记 临时想法", exact: true }).click();
  await panel.getByRole("textbox", { name: "随记名称", exact: true }).fill("新的想法");
  await panel.getByRole("button", { name: "确定", exact: true }).click();
  await expect(panel.getByRole("button", { name: "重命名随记 新的想法", exact: true })).toBeVisible();
  await page.reload();
  if (!await panel.isVisible()) await rail.getByRole("button", { name: "随记", exact: true }).click();
  await expect(panel.getByRole("region", { name: "近期", exact: true }).locator(".notes-panel-row")).toHaveCount(2);
  const saved = await page.evaluate(async () => {
    const path = "/src/lib/api.ts";
    const { api } = await import(/* @vite-ignore */ path);
    return (await api.docs.listByPath("ideas/notes/近期")).map(note => ({ title: note.title, content: note.content }));
  });
  expect(saved.map(note => note.title).sort()).toEqual(["待办随记", "新的想法"].sort());
  expect(JSON.stringify(saved.find(note => note.title === "待办随记")!.content)).toContain("完成回归");
  const todoOps = saved.find(note => note.title === "待办随记")!.content.ops.filter(op => typeof op.attributes?.taskChecked === "boolean");
  expect(todoOps.map(op => op.attributes!.taskChecked)).toEqual([true, false]);
});

test("手机左侧抽屉可切换随记，新建后收起并可使用 /todo 回车", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 760 });
  await page.goto("/");
  await expect(page.locator(".note-editor")).toBeVisible();
  const sidebar = await openDocumentSidebar(page);
  await sidebar.getByRole("button", { name: "随记", exact: true }).click();
  const panel = page.getByRole("region", { name: "随记列表", exact: true });
  await expect(panel).toBeVisible();
  await expect(sidebar.locator(".desktop-panel-content")).toBeHidden();
  await panel.getByRole("button", { name: "新建随记", exact: true }).click();
  await expect(sidebar).toHaveClass(/sidebar-hidden/);
  const editor = page.locator(".ProseMirror");
  await editor.pressSequentially("/todo");
  await editor.press("Enter");
  await expect(editor.getByRole("checkbox", { name: "任务完成状态" })).toHaveAttribute("aria-checked", "false");
  const popup = await openMobileDocumentPopup(page);
  await popup.getByRole("button", { name: "随记", exact: true }).click();
  await expect(popup).toBeHidden();
  await expect(panel).toBeVisible();
  await expect(sidebar).not.toHaveClass(/sidebar-hidden/);
});
