import { expect, test } from "@playwright/test";
import { PDFDocument } from "pdf-lib";
import { createEpubFixture } from "./helpers/reader-fixtures";

test.use({ viewport: { width: 390, height: 760 }, hasTouch: true });

test("PDF 锁定宽度跨页面尺寸、方向和重新打开保持", async ({ page }) => {
  const pdf = await PDFDocument.create();
  pdf.addPage([600, 800]).drawText("First");
  pdf.addPage([900, 600]).drawText("Second");
  await page.goto("/");
  await page.getByTitle("设置").click();
  await page.getByRole("button", { name: /^阅读资料库/ }).click();
  await page.locator('input[accept="application/pdf,.pdf"]').setInputFiles({ name: "width.pdf", mimeType: "application/pdf", buffer: Buffer.from(await pdf.save()) });
  await page.getByRole("button", { name: "PDF 阅读设置", exact: true }).click();
  await page.getByLabel("缩小 PDF", { exact: true }).click();
  await page.getByRole("button", { name: "锁定当前宽度", exact: true }).click();
  const ratio = () => page.locator(".pdf-page-surface").first().evaluate(el => el.getBoundingClientRect().width / Math.max(160, document.querySelector(".pdf-page-viewport")!.clientWidth - 24));
  const locked = await ratio();
  await page.getByRole("button", { name: "关闭 PDF 阅读设置", exact: true }).click();
  await page.getByRole("button", { name: "下一页", exact: true }).click();
  await expect(page.locator(".pdf-text-layer")).toContainText("Second");
  await expect.poll(ratio).toBeCloseTo(locked, 2);
  await page.setViewportSize({ width: 760, height: 390 });
  await expect.poll(ratio).toBeCloseTo(locked, 2);
  await page.getByRole("button", { name: "关闭 PDF 阅读器", exact: true }).click();
  await page.getByTitle("设置").click();
  await page.getByRole("button", { name: /^阅读资料库/ }).click();
  await page.getByRole("button", { name: /打开 width.pdf/ }).click();
  await expect(page.locator(".pdf-text-layer")).toContainText("Second");
  await expect.poll(ratio).toBeCloseTo(locked, 2);
  await page.getByRole("button", { name: "PDF 阅读设置", exact: true }).click();
  await expect(page.getByRole("button", { name: "解锁宽度", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "纵向", exact: true }).click();
  await page.getByRole("button", { name: "关闭 PDF 阅读设置", exact: true }).click();
  const first = page.locator('.pdf-page-surface[data-pdf-page="1"]');
  await first.evaluate(el => el.scrollIntoView({ block: "start" }));
  await expect(first.locator(".pdf-text-layer")).toContainText("First");
  await expect.poll(ratio).toBeCloseTo(locked, 2);
  await first.dispatchEvent("dblclick");
  await expect.poll(ratio).toBeCloseTo(locked, 2);
  await page.getByRole("button", { name: "PDF 阅读设置", exact: true }).click();
  await page.getByRole("button", { name: "适宽", exact: true }).click();
  await expect(page.getByRole("button", { name: "锁定当前宽度", exact: true })).toHaveAttribute("aria-pressed", "false");
});

test("EPUB 正文宽度换章、重新打开保持且独立于字号", async ({ page }) => {
  await page.goto("/");
  await page.getByTitle("设置").click();
  await page.getByRole("button", { name: /^阅读资料库/ }).click();
  await page.locator('input[accept="application/epub+zip,.epub"]').setInputFiles({ name: "width.epub", mimeType: "application/epub+zip", buffer: createEpubFixture() });
  await page.getByRole("button", { name: "EPUB 阅读设置", exact: true }).click();
  await page.getByRole("slider", { name: "EPUB 正文宽度" }).fill("80");
  const body = page.frameLocator(".epub-chapter-frame").locator("body");
  const width = () => body.evaluate(el => el.getBoundingClientRect().width / el.ownerDocument.documentElement.clientWidth);
  await expect.poll(width).toBeCloseTo(0.8, 2);
  await page.getByRole("button", { name: "关闭 EPUB 阅读设置", exact: true }).click();
  await page.getByRole("button", { name: "下一章", exact: true }).click();
  await expect(body).toContainText("第二章");
  await expect.poll(width).toBeCloseTo(0.8, 2);
  await page.getByRole("button", { name: "关闭 EPUB 阅读器", exact: true }).click();
  await page.getByTitle("设置").click();
  await page.getByRole("button", { name: /^阅读资料库/ }).click();
  await page.getByRole("button", { name: /打开 Nine Rings EPUB MVP/ }).click();
  await expect(body).toContainText("第二章");
  await expect.poll(width).toBeCloseTo(0.8, 2);
  await expect(page.frameLocator(".epub-chapter-frame").locator("html")).toHaveCSS("font-size", "16px");
  await page.getByRole("button", { name: "EPUB 阅读设置", exact: true }).click();
  await expect(page.getByRole("slider", { name: "EPUB 正文宽度" })).toHaveValue("80");
  await page.getByRole("button", { name: "恢复默认宽度", exact: true }).click();
  await expect.poll(width).toBeCloseTo(1, 2);
});
